name: DEV Builds
trigger:
- develop

stages:
- stage: BuildIos
  displayName: Build for iOS
  jobs:
  - job: Build
    displayName: Build the app
    pool:
      vmImage: 'macOS-10.14'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - script: |
        npm install -g titanium alloy
      displayName: 'Install the Titanium CLI + Alloy'
    - script: |
        echo "y" | titanium sdk install latest
      displayName: 'Install latest Titanium SDK'
    - script: |
        perl -pi -e 's/<guid>xxx/<guid>$(TIAPP_GUID)/g' tiapp.xml
      displayName: 'Replace the App GUID'
    - script: |
        titanium build -p ios --build-only
      displayName: 'Build the iOS app'
    - task: PublishPipelineArtifact@1
      inputs:
        path: $(System.DefaultWorkingDirectory)/build/iphone/build/Products/Debug-iphonesimulator
        artifact: HellocdIos

- stage: BuildAndroid
  displayName: Build for Android
  dependsOn: []
  jobs:
  - job: Build
    displayName: Build the app
    pool:
      vmImage: 'macOS-10.14'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - script: |
        npm install -g titanium alloy
      displayName: 'Install the Titanium CLI + Alloy'
    - script: |
        echo "y" | titanium sdk install latest
      displayName: 'Install latest Titanium SDK'
    - script: |
        titanium info
      displayName: '[Debug] Check Titanium environment'
    - script: |
        perl -pi -e 's/<guid>xxx/<guid>$(TIAPP_GUID)/g' tiapp.xml
      displayName: 'Replace the App GUID'
    - script: |
        perl -pi -e 's/android:debuggable="false"/android:debuggable="true"/g' tiapp.xml
      displayName: 'Active Android Debug mode'
    - script: |
        titanium build -p android --build-only
      displayName: 'Build the Android app'
    - task: PublishPipelineArtifact@1
      inputs:
        path: $(System.DefaultWorkingDirectory)/build/android/bin/HelloCD.apk
        artifact: HellocdAndroid
